services:
  backend:
    container_name: aethernote-be
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - redis
    ports:
      - "127.0.0.1:${BACKEND_LISTENING_PORT}:${BACKEND_LISTENING_PORT}"
    networks:
      - internal

  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - internal

networks:
  internal:
    driver: bridge