services:
  backend:
    container_name: aethernote-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - redis
    networks:
      - internal

  frontend:
    container_name: aethernote-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks:
      - internal

  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - internal

  nginx:
    container_name: reverse-proxy
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "${LISTENING_PORT}:80"
    depends_on:
      - backend
      - frontend
    networks:
      - internal
    environment:
      BACKEND_PORT: "8080"
      FRONTEND_PORT: "80"

networks:
  internal:
    driver: bridge
