services:
  app:
    container_name: aethernote
    build: .
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8000:${LISTEN_PORT}"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      PORT: ${LISTEN_PORT}
    networks:
      - internal

  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - internal

networks:
  internal:
    driver: bridge