FROM node:22-alpine as build

WORKDIR /app

COPY frontend/package.json ./
COPY frontend/package-lock.json ./

RUN npm install

COPY frontend ./

RUN npm run build

FROM nginx:alpine

COPY nginx.conf.frontend /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]